### ISSUE TITLE
Recording todo

### ISSUE THREAD

**Issue by mixmixmix** [mixmixmix/parrtraks#1]
- [ ] - allow changing resolutions
- [ ] - allow changing rotation
- [ ] - find good encoding 
h264,quality 10
 - [x] - automatically add hostname to recording
- [ ] - set up manual white balance
- [ ] autimatically create a new file after an hour of recording and copy previous one over (?) how
